# Site settings
title: Stefan Kapferer
header-img: img/home-bg.jpg
email: stefan@kapferer.ch
description: "Stefan Kapferer's Blog"
baseurl: ""
url: "http://blog.kapfi.ch"
twitter_username: skapfi
github_username:  stefan-ka
facebook_username:  ""

# Build settings
markdown: kramdown
highlighter: pygments
permalink: pretty
paginate: 5
exclude: ["less","node_modules","Gruntfile.js","package.json","README.md"]
