# Site settings
title: Stefan Kapferer
header-img: img/home-bg.jpg
email: stefan@kapferer.ch
description: "Stefan Kapferer's Homepage"
baseurl: ""
url: "http://www.kapferer.ch"
twitter_username: stefankapferer
github_username:  stefan-ka
linkedin_username:  stefankapferer

# Build settings
markdown: kramdown
highlighter: rouge
permalink: pretty
gems: [jekyll-paginate]
paginate: 5
exclude: ["less","node_modules","Gruntfile.js","package.json","README.md"]
